#!/usr/bin/python

n = int(raw_input())

i = 0

while i < n :
    i+=1
    a = raw_input().split(' ')
    x = int(a[0])
    y = int(a[1])
    ans = float(x*y)
    if x%2 == 1 and y%2 == 1:
        ans += 0.41
    print 'Scenario #%d:'%(i)
    print "%.2f"%(ans)
    print
